services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
    secrets:
      - db_name
      - db_user_name
      - db_user_pass
    volumes:
      - wp_data:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    restart: always

  wordpress:
    container_name: wp
    build:
      context: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    env_file: .env
    secrets:
      - db_name
      - db_user_name
      - db_user_pass
      - wp_admin_user
      - wp_admin_pass
      - wp_admin_mail
      - wp_author_user
      - wp_author_pass
      - wp_author_mail
    restart: always
    expose:
      - "9000"

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp_files:/var/www/html
    restart: always

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ribana-b/data
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ribana-b/data

networks:
  inception:
    driver: bridge

secrets:
  db_name:
    file: ../secrets/db_name.txt
  db_user_name:
    file: ../secrets/db_user_name.txt
  db_user_pass:
    file: ../secrets/db_user_pass.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt
  wp_admin_mail:
    file: ../secrets/wp_admin_mail.txt
  wp_author_user:
    file: ../secrets/wp_author_user.txt
  wp_author_pass:
    file: ../secrets/wp_author_pass.txt
  wp_author_mail:
    file: ../secrets/wp_author_mail.txt
